### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sali-k** [sali-k/furima-29183#9]
#URL
https://furima-29183.herokuapp.com/

#Basic認証のIDとパスワード
ID: admin
パスワード: smile83

#出品者用のメールアドレスとパスワード
メールアドレス: seller1234@gmail.com
パスワード: seller1234

#購入者用のメールアドレスとパスワード
メールアドレス: buyer1234@gmail.com
パスワード: buyer1234

#購入用カードの番号・期限・セキュリティコード
購入用カードの番号: 4242424242424242
期限: 12/24
セキュリティコード: 123

**Comment by tech-oa** [comment]
sali-kさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
> セキュリティコード: 12/24

こちらのセキュリティコードに間違いがあるようですので、購入機能を確認することができません。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sali-k** [comment]
大変失礼いたしました！こちらの記述ミスでございます。上記のセキュリティーコードを123と訂正いたしました。
お手数をお掛けしますが、再度ご確認をお願いいたします。

**Comment by tech-taro** [comment]
sali-kさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、完成要件は全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

必須ではありませんが、余裕があればこちらも修正し、よりクオリティの高いアプリケーションにしていただきたく存じます。（提出はしなくて大丈夫です。）
・商品削除機能の確認
購入済みの商品を削除しようとするとエラーになる

※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。

**Comment by sali-k** [comment]
ご確認とLGTMありがとうございます！おかげさまでここまで来れました！
とても嬉しいです！
商品削除機能の確認、承知いたしました！
今後とも頑張っていきます！ありがとうございました！
